blank_issues_enabled: true
contact_links:
  - name: QQ 群
    url: https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=QZmmrmSQqSAyI8Mo5NHAMc9l6TejcBrw&authKey=mQrh5avqMDc09GunNdtCmuN5tk9UynOekkjHxfuKPjhN4ELWBMJN5edaYw51UXbQ&noverify=0&group_code=735910197
    about: 进群讨论，不适合当 Issue 的问题可以先在这里问
  - name: Telegram
    url: https://t.me/+6JhB2iRjjDExYWM1
    about: 频道与讨论
